[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p routers/chatgpt_module/temp_audio", "mkdir -p routers/audio_transcription_module/temp_audio"]

[start]
cmd = "python bot.py" 